### ISSUE TITLE
Manuscript revisions

### ISSUE THREAD

**Issue by pbreheny** [areisett/reviewPLMM_paper#2]
- [x] "directly jumps into a statistical question"  More discussion of application in general, and especially up front.
- [x] "should be clearer descriptions on when the reviewed approaches can/cannot be applied"; be more explicit here?
- [x] More background on lasso
- [x] More discussion of software.  Add a small section?
- [x] More discussion of nonlinear models. In particular, is logistic regression practical?
- [x] "may be of interest to know more about the statistical properties"...I don't know what this means.  Like, theoretical properties?  Maybe we can discuss?  Mention Rohe and/or Buhlmann?
- [x] "Data examples are recommended"; "more realistic simulation scenarios...100,000s of SNPs"; Let's handle this with a genome-scale single replication study to address both points. Simulate vanderwas phenotype + spike in 50,000 snps with effect on simulated phenotype (select 1000)? How well do these methods do at finding these SNPs? Like a real data analysis... case study - single replicate of a genome wide analysis here's how it turned out. Compare with regular lasso, PC-lasso. 
- [x] Finalize figures, check PRC curve issues for PC-lasso
- [x] Write methods section for genome-wide analysis
- [x] Write results section for genome-wide analysis
- [x] penalty parameter selection; also a tough one. We need to say more, but not a great deal is known.
- [x] Fig1, Table1 captions should specify # of replications and which SNPs are included (all 1000 or only those selected?) - do this for all figures, not just Fig1 Table1? 
- [x] "For Figure 1, it would be helpful to have error bars included in bar plots." - described in updated caption. additional line in legend seems redundant.
- [x] "there is a typo in Eqn 15."
- [x] Get latex version working on genetic epi portal
- [x] **Patrick** to clip pdf tikz plots and convert to eps files
- [x] Point-by-point responses
- [x] New cover letter
- [x] Resubmit

**Comment by areisett** [comment]
Going to close this since we finished everything and have published
